### PR TITLE
feat: immediate option to skip initial fetch

### PR DESCRIPTION
**Pull request by johannschopplich**

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
How exactly does this play with suspense? Can you elaborate a bit on the reasonings for this change?

Thanks!!

**Comment by johannschopplich** [comment]
You're right, this probably won't make much sense in a suspense setup. I needed a way to block the initial fetch for a search page – on initial page view and without any user input, no data should be searched. But as soon as a search query hits the keyboard, the URL changes and the TurboVue computed key will initiate a search.

You can close this, of course, if it doesn't make much sense! 🙂

**Comment by ConsoleTVs** [comment]
Ah! A quick tip, if your key resolves to undefined, false or throws, it wont fetch!

**Comment by ConsoleTVs** [comment]
@johannschopplich Out if curiosity, what made you start using this pckage? It's fairly new and there is little docs besides those on https://erik.cat

**Comment by johannschopplich** [comment]
@ConsoleTVs Thanks, already took a look into the docs! I will stick to a fork for a non-suspense setup for now. I plan to migrate the app to a suspenseful setup in the future. I guess my use-case doesn't need to be handled by this package.

Since `vswr` I follow your work. I highly appreciate your lean approaches and clean coding style. Learning a lot from your repos while reading. That's why I dig into the new Studio Lambda repos once you created them. Thank you for all of your open source work!

**Comment by ConsoleTVs** [comment]
@johannschopplich 

Wow that's awesome to hear. `vswr` is still well supported AND also have suspense support. Note that suspense is cool because it can do SSR quite easy.  Both packages support it atm, but turbo-query is my evolution of swrev (the underlying pkg of vswr). `turbo-query` is actually fully tested with code coverage on 100%, so we're creating those new packages here to evolve them (but they are pre v.1). Do you think I should add non-suspense support to this vue fork? In Solid.JS you get this for free using their primitives but with vue its either throwing / awaiting promises on the setup function or using watchers. So, should I make a non-suspense function?

As a side note, I've been thinking about an `enabled` flag rather than having to throw / return false or undefined in the key. Thoughts? (returning false / undefined / throwing is how its done in vercel's `swr` while enabled flag is mostly from `react-query`)

**Pull request closed without merging**
